// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson16eb09bcDecodeShortLinkInternalDeliveryHttpDto(in *jlexer.Lexer, out *CreateLinkResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "short_link":
			out.ShortLink = string(in.String())
		case "expires_at":
			out.ExpiresAt = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16eb09bcEncodeShortLinkInternalDeliveryHttpDto(out *jwriter.Writer, in CreateLinkResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"short_link\":"
		out.RawString(prefix[1:])
		out.String(string(in.ShortLink))
	}
	{
		const prefix string = ",\"expires_at\":"
		out.RawString(prefix)
		out.String(string(in.ExpiresAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateLinkResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16eb09bcEncodeShortLinkInternalDeliveryHttpDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateLinkResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16eb09bcEncodeShortLinkInternalDeliveryHttpDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateLinkResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16eb09bcDecodeShortLinkInternalDeliveryHttpDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateLinkResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16eb09bcDecodeShortLinkInternalDeliveryHttpDto(l, v)
}
func easyjson16eb09bcDecodeShortLinkInternalDeliveryHttpDto1(in *jlexer.Lexer, out *CreateLinkRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "link":
			out.Link = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16eb09bcEncodeShortLinkInternalDeliveryHttpDto1(out *jwriter.Writer, in CreateLinkRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"link\":"
		out.RawString(prefix[1:])
		out.String(string(in.Link))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateLinkRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16eb09bcEncodeShortLinkInternalDeliveryHttpDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateLinkRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16eb09bcEncodeShortLinkInternalDeliveryHttpDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateLinkRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16eb09bcDecodeShortLinkInternalDeliveryHttpDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateLinkRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16eb09bcDecodeShortLinkInternalDeliveryHttpDto1(l, v)
}
